<?php

namespace Fresh\LeboncoinBundle\Repository;

/**
 * AnnonceurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceurRepository extends \Doctrine\ORM\EntityRepository
{
}
