<?php

namespace Fresh\LeboncoinBundle\Repository;

/**
 * CathegorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CathegorieRepository extends \Doctrine\ORM\EntityRepository
{
}
